In [19]:
from google.colab import drive
from pandas import DataFrame
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
import numpy as nptest
import pandas as pd

#drive.mount('/content/drive')

df = pd.read_csv('https://raw.githubusercontent.com/jantapongb/AI-Kmeans-ANN/master/AllTrainDataNormalAbnormal.csv')
#print(df)
kmeans = KMeans(n_clusters=3).fit(df)
centroids = kmeans.cluster_centers_
print(centroids)
#print(kmeans.labels_)

#sample_test=np.array([942,19791,16,95,1446,27729,22,45,2945,56525,48,31])     #--Normal
sample_test=nptest.genfromtxt('https://raw.githubusercontent.com/jantapongb/AI-Kmeans-ANN/master/TestingDataSetColapMix.csv',delimiter=',')
second_test=sample_test.reshape(30, 4)            #--Split 30 Row 4 Colume
print(kmeans.predict(second_test))

comment_label = kmeans.labels_
comment_cluster_df = pd.DataFrame(df)
#comment_cluster_df['comment_label'] = np.nan
comment_cluster_df['Clustering'] = comment_label

#print(comment_cluster_df )              #----- Show Output Data Label Custered

print('Saving to CSV')
#comment_cluster_df.to_csv('/content/drive/Shared drives/PROFRESSIONAL_FIRST/DOCTOR/TERM 2/AI/COLAP/OutputWithCluster.csv', index=False)
comment_cluster_df.to_csv('OutputWithCluster.csv', index=False)

[[2.84632750e+03 5.69140850e+04 4.50700000e+01 3.15375000e+01]
 [1.42392750e+03 2.85300775e+04 2.15325000e+01 4.74400000e+01]
 [9.47232500e+02 1.90208950e+04 1.49575000e+01 9.47600000e+01]]
[0 2 0 2 2 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 1 1 1 1 1 1 1 1 1 1]
Saving to CSV
